#!/bin/bash

echo "navigation to target folder"
cd /var/www/modmod

echo "enabling xdebug"
enable_xdebug

echo "running unit tests with coverage"
XDEBUG_MODE=coverage ./vendor/bin/phpunit -c Build/phpunit.xml --do-not-cache

echo "disabling xdebug"
disable_xdebug
