services:
    web:
        environment:
            - EXTENSION_KEY=modmod
            - PACKAGE_NAME=teamneusta/modmod

            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_USER=root
            - TYPO3_INSTALL_DB_DBNAME=db
            - TYPO3_INSTALL_DB_PASSWORD=root
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_PORT=3306
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=0
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=Admin123!
            - TYPO3_INSTALL_SITE_NAME=EXT:modmod Dev Environment
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
            - TYPO3_CONTEXT=Development
            - TYPO3_PATH_WEB=/var/www/html/public
        volumes:
            - type: bind
              source: ../
              target: /var/www/modmod
              consistency: cached
volumes:
    v12-data:
        name: "${DDEV_SITENAME}-v12-data"
